#pragma once
#define SOL 0
#define KY 1
#define MAY 2
#define AXL 3
#define CHIPP 4
#define POTEMPKIN 5
#define FAUST 6
#define MILLIA 7
#define ZATO 8
#define RAM 9
#define LEO 10
#define NAGO 11
#define GIOVANNA 12
#define ANJI 13
#define INO 14
#define GOLDLEWIS 15
#define JACKO 16
#define HC 17
#define BAIKEN 18
#define TESTAMENT 19
#define BRIDGET 20
#define SIN 21
#define BEDMAN 22
#define ASUKA 23
#define JOHNNY 24
#define ELPHELT 25
#define ABA 26
#define SLAYER 27
#define DIZZY 28
#define VENOM 29